services:
    GaylordP\EmailBundle\EventListener\SetFromListener:
        arguments:
            - '@twig'
            - '@doctrine.orm.entity_manager'
            - '%email%'
        tags:
            - 'kernel.event_subscriber'

    GaylordP\EmailBundle\Repository\EmailRepository:
        arguments:
            - '@doctrine'
        tags:
            - 'doctrine.repository_service'
